### ISSUE TITLE
Add upper bound to `errors` dependency

### ISSUE THREAD

**Issue by Gabriel439** [k0ral/hbro#13]
`errors-2.0` will switch to use `ExceptT` instead of `EitherT`.  If that will break your package then add an upper bound of `errors < 2.0` to your dependencies.

**Comment by k0ral** [comment]
It won't break anything as the impacted functions from `errors` aren't currently used in `hbro`. Thank you for the warning :) .

**Comment by Gabriel439** [comment]
Thanks for checking!
